#pragma pop_macro("LLVM_VERSION_UNIFY")
#pragma pop_macro("LLVM_VERSIOC_REST_UNIFY")
#pragma pop_macro("LLVM_VERSION_UNIFY_FINALIZE")


#pragma pop_macro("LLVM_VERSION_REST_INCLUDE")
//#if not LLVM_VERSION_REST_INCLUDE
//#undef LLVM_VERSION_REST_INCLUDE
//#endif


#pragma pop_macro("LLVM_VERSION_40_INCLUDE")
//#if not LLVM_VERSION_40_INCLUDE
//#undef LLVM_VERSION_40_INCLUDE
//#endif

#pragma pop_macro("LLVM_VERSION_40_UNIFY")
//#if not LLVM_VERSION_40_UNIFY
//#undef LLVM_VERSION_40_UNIFY
//#endif


#pragma pop_macro("LLVM_VERSION_50_INCLUDE")
//#if not LLVM_VERSION_50_INCLUDE
//#undef LLVM_VERSION_50_INCLUDE
//#endif

#pragma pop_macro("LLVM_VERSION_50_UNIFY")
//#if not LLVM_VERSION_50_UNIFY
//#undef LLVM_VERSION_50_UNIFY
//#endif


#pragma pop_macro("LLVM_VERSION_60_INCLUDE")
//#if not LLVM_VERSION_60_INCLUDE
//#undef LLVM_VERSION_60_INCLUDE
//#endif

#pragma pop_macro("LLVM_VERSION_60_UNIFY")
//#if not LLVM_VERSION_60_UNIFY
//#undef LLVM_VERSION_60_UNIFY
//#endif


#pragma pop_macro("LLVM_VERSION_70_INCLUDE")
//#if not LLVM_VERSION_70_INCLUDE
//#undef LLVM_VERSION_70_INCLUDE
//#endif

#pragma pop_macro("LLVM_VERSION_70_UNIFY")
//#if not LLVM_VERSION_70_UNIFY
//#undef LLVM_VERSION_70_UNIFY
//#endif


#pragma pop_macro("LLVM_VERSION_80_INCLUDE")
//#if not LLVM_VERSION_80_INCLUDE
//#undef LLVM_VERSION_80_INCLUDE
//#endif

#pragma pop_macro("LLVM_VERSION_80_UNIFY")
//#if not LLVM_VERSION_80_UNIFY
//#undef LLVM_VERSION_80_UNIFY
//#endif


#pragma pop_macro("LLVM_VERSION_90_INCLUDE")
//#if not LLVM_VERSION_90_INCLUDE
//#undef LLVM_VERSION_90_INCLUDE
//#endif

#pragma pop_macro("LLVM_VERSION_90_UNIFY")
//#if not LLVM_VERSION_90_UNIFY
//#undef LLVM_VERSION_90_UNIFY
//#endif