#ifndef BOAAA_MACROLIST_MACROLIST_H
#define BOAAA_MACROLIST_MACROLIST_H

#define BOAAA_MACROLIST_EVAL_(X) X
#define BOAAA_MACROLIST_EVAL(X) BOAAA_MACROLIST_EVAL_(X)

#define BOAAA_MACROLIST_UNDEF 0
#endif  
