#ifndef BOAAA_SUPPORTED_LLVM_VERSION_H
#define BOAAA_SUPPORTED_LLVM_VERSION_H

#define NOT_SUPPORTED_LLVM_VERSION

#ifdef LLVM_VERSION_40
#undef NOT_SUPPORTED_LLVM_VERSION
#endif //!LLVM_VERSION_40

#ifdef LLVM_VERSION_50
#undef NOT_SUPPORTED_LLVM_VERSION
#endif //!LLVM_VERSION_50

#ifdef LLVM_VERSION_90
#undef NOT_SUPPORTED_LLVM_VERSION
#endif //!LLVM_VERSION_90

#endif //BOAAA_SUPPORTED_LLVM_VERSION_H