#ifndef BOAAA_STRUCT_HELP_H
#define BOAAA_STRUCT_HELP_H

#define BOAAA_MEMBER(TYPE, VALUE)			TYPE m_##VALUE;
#define BOAAA_SETTER_HELP(TYPE, VALUE)		inline void set_##VALUE(TYPE value) { m_##VALUE = value; }
#define BOAAA_GETTER_HELP(TYPE, VALUE)		inline TYPE get_##VALUE() { return m_##VALUE; }

#define BOAAA_SETTER_DIFF(MEMTYPE, TYPE, VALUE)			\
BOAAA_MEMBER(MEMTYPE, VALUE)							\
BOAAA_SETTER_HELP(TYPE, VALUE)		

#define BOAAA_SETTER(TYPE, VALUE)						\
BOAAA_MEMBER(TYPE, VALUE)								\
BOAAA_SETTER_HELP(TYPE, VALUE)

#define BOAAA_GETTER_DIFF(MEMTYPE, TYPE, VALUE)			\
BOAAA_MEMBER(MEMTYPE, VALUE)							\
BOAAA_GETTER_HELP(TYPE, VALUE)

#define BOAAA_GETTER(TYPE, VALUE)						\
BOAAA_MEMBER(TYPE, VALUE)								\
BOAAA_GETTER_HELP(TYPE, VALUE)							\

#define BOAAA_SETTER_GETTER_DIFF(MEMTYPE, TYPE, VALUE)	\
BOAAA_MEMBER(MEMTYPE, VALUE)							\
BOAAA_GETTER_HELP(TYPE, VALUE)							\
BOAAA_SETTER_HELP(TYPE, VALUE)							\

#define BOAAA_SETTER_GETTER(TYPE, VALUE)				\
BOAAA_MEMBER(TYPE, VALUE)								\
BOAAA_GETTER_HELP(TYPE, VALUE)							\
BOAAA_SETTER_HELP(TYPE, VALUE)

#endif