function(boaaa_copy_and_rename _SOURCE_DIR _SOURCE _DESTINATION_DIR _DESTINATION)
	set(__tmp_foulder "${CMAKE_CURRENT_SOURCE_DIR}/__tmp")
	if(EXISTS ${__tmp_foulder})
		set(__tmp_foulder "${__tmp_foulder}__tmp")
		if (EXISTS ${__tmp_foulder})
			message(FATAL_ERROR "|| can`t rename because cant create tmp foulder")
		endif()
	endif()
	file(MAKE_DIRECTORY ${__tmp_foulder})
	file(COPY "${_SOURCE_DIR}/${_SOURCE}" DESTINATION "${__tmp_foulder}")
	file(RENAME "${__tmp_foulder}/${_SOURCE}" "${_DESTINATION_DIR}/${_DESTINATION}")
	file(REMOVE_RECURSE ${__tmp_foulder})
endfunction()